### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by runely** [runely/calendar-homey#179]
getNextEvent assumes an event is found. When 0 events from calendar is imported, getNextEvent will return an emtpy object...

```javascript
app.triggerEvents: Failed in updateTokens Promise: TypeError: Cannot read property 'start' of undefined
    at /handlers/triggers.js:122:44
    at Array.map (<anonymous>)
    at updateFlowTokens (/handlers/triggers.js:117:33)
    at /handlers/triggers.js:334:9
    at new Promise (<anonymous>)
    at AsyncFunction.module.exports.updateTokens (/handlers/triggers.js:331:12)
    at IcalCalendar.triggerEvents (/app.js:186:26)
    at CronTask.<anonymous> (/app.js:232:47)
    at CronTask.emit (events.js:311:20)
    at CronTask.EventEmitter.emit (domain.js:482:12)
```

**Comment by runely** [comment]
Implemented checking for existens on event
